### ISSUE TITLE
Test/fix collectDiscards()

### ISSUE THREAD

**Issue by ideascape** [Hansigzandrinovka/BlackJack368Project#11]
I don't really know if this is working. I think it probably is, but we should check. console.log the total number of cards in the deck (active+discards) at the beginning and end of the game (after discards have been collected) and see if they match.

**Comment by mbechtel2** [comment]
The problem was that you didn't reassign discards when you added the players hand to it. I got it to work by changing it to discards = discards.concat(this.players[i].getPlayerHand());. On a side note, resolveGame() is called twice at the end of both playTurns and makeMove. I commented the one in playTurns out but I don't know which one is supposed to be called.

**Comment by ideascape** [comment]
Cool. So the deck total matches before and after now?

Good catch on resolveGame. We can get rid of the one in makeMove.

**Comment by mbechtel2** [comment]
I think it works now. I log the length of active+discard before the cards are dealt in startGame and after they are collected in resolveGame, and both cases always gave me 208, which is what I was expecting.

**Comment by ideascape** [comment]
Excellent, feel free to mark it as closed.
